apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace}}
  labels:
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    app.openshift.io/runtime: python
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $value := $.Values.labels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- range $key, $value := $.Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Values.name }}-container
          ports:
            - containerPort: "{{ $.Values.service.port }}"
              protocol: TCP
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: LLM_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: llm-sa-secret
                  key: endpoint
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-sa-secret
                  key: token
            - name: model_name:
              value: {{ $.Values.modelName }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}